Innlagt på institusjon added to søknad
navikt/su-se-bakover pull request #109
Opened 2020-11-05 13:04 UTC by RamziAbuQassim

2020-11-05 14:42 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnhold.kt
> +    val datoForInnlegelse: LocalDate?,
Her mister vi konteksten instutisjon da. Kunne vi wrappet de 3 feltene i en type?

2020-11-05 15:00 UTC, RamziAbuQassim commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnhold.kt
> +    val datoForInnlegelse: LocalDate?,
👍

2020-11-06 07:11 UTC, ingara requested changes

2020-11-06 07:11 UTC, ingara commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnhold.kt
> +    val datoForInnlegelse: LocalDate,
```suggestion
    val datoForInnleggelse: LocalDate,
```

2020-11-06 07:11 UTC, ingara commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/SøknadInnholdTestdataBuilder.kt
> +                datoForInnlegelse = LocalDate.of(2020, JANUARY, 1),
```suggestion
                datoForInnleggelse = LocalDate.of(2020, JANUARY, 1),
```

2020-11-06 07:11 UTC, ingara commented on web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadJsonTest.kt
> +                    "datoForInnlegelse": "2020-01-01",
```suggestion
                    "datoForInnleggelse": "2020-01-01",
```

2020-11-06 07:57 UTC, christianmosveen approved these changes
Bare fiks de skrivefeilene @ingara påpekte så er du good to go!

2020-11-06 08:38 UTC, ingara approved these changes

2020-11-06 08:53 UTC, merged