Saksbehandler historikk
navikt/su-se-bakover pull request #1237
Opened 2023-01-25 16:06 UTC by RamziAbuQassim

2023-01-26 09:25 UTC, hestad commented on database/src/main/kotlin/no/nav/su/se/bakover/database/søknadsbehandling/SøknadsbehandlingHistorikkJson.kt
> +    FullførBosituasjon,
```suggestion
    FullførtBosituasjon,
```

2023-01-26 09:28 UTC, hestad commented on database/src/main/kotlin/no/nav/su/se/bakover/database/søknadsbehandling/SøknadsbehandlingHistorikkJson.kt
> +    Formue,
Tenker vi ikke trenger duplikater her. Vi har både OppdatertFormue og et formuevilkår 🤷‍♂️ Hvilke brukes i praksis?

2023-01-26 11:32 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Saksbehandlingshistorikk.kt
> +    val historikk: List<T>
Validering av f.eks sortering og innhold må gjøres av en klasse, men selve funksjonen kan ligge her i tilfelle det er fler som arver dette interfacet.

2023-01-26 11:42 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
> +                        søknadsbehandlingsHistorikk = behandling.søknadsbehandlingsHistorikk.leggTilNyHendelse(
Kunne trekt ut denne i en variabel siden den brukes flere ganger

2023-01-26 11:45 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandlingshistorikk.kt
> +    object OppdatertFormue : SøknadsbehandlingsHandling
Kan denne slettes?

2023-01-26 11:47 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandlingshistorikk.kt
> +    object OppdatertFradrag : SøknadsbehandlingsHandling
```suggestion
    object OppdatertFradragsgrunnlag : SøknadsbehandlingsHandling
```
Siden vi har 2 konsepter rundt fradrag. Selve grunnlaget som saksbehandleren sender inn, som er et subset av selve fradragene brukeren sender inn. I dag er det vel en og samme enum, men burde vært 2.

2023-01-26 11:54 UTC, hestad commented on domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/StatusovergangTest.kt
> +                        nySøknadsbehandlingshendelse(handling = SøknadsbehandlingsHandling.OppdatertFradrag),
Jeg tror vi bør legge inn denne handlingen slik atvi kun får en handling dersom saksbehandler utfører den. Jeg gjetter på at vi har lagt oss for langt inn.

2023-01-26 11:59 UTC, hestad commented on domain/src/test/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/StatusovergangTest.kt
> +                            nySøknadsbehandlingshendelse(handling = SøknadsbehandlingsHandling.SendtTilAttestering),
Jeg ser tanken med å finne et felles ord for saksbehandler og attestant, og ha en liste med begge sine handlinger. Men det kan vi tenke på til siden.

2023-01-26 12:23 UTC, hestad commented on test-common/src/main/kotlin/SøknadsbehandlingTestData.kt
> +    søknadsbehandlingsHistorikk: Søknadsbehandlingshistorikk = nySøknadsbehandlingshistorikkAlleVilkårMedBosituasjonOgFradrag(
Det føles litt rart at man kan definere denne. Da får vi en større mismatch mellom produksjons- og testkoden. Gjelder for hele fila.

2023-01-26 12:24 UTC, hestad commented on test-common/src/main/kotlin/SøknadsbehandlingsHistorikkTestData.kt
> + * @param clock ignorerer clock hvis vi sender med tidspunkt
```suggestion
 * @param tidspunkt ignorerer clock hvis vi sender med tidspunkt
```

2023-01-26 12:28 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandlingshistorikk.kt
> +    data class OppdatertVilkår(val inngangsvilkår: Inngangsvilkår) : SøknadsbehandlingsHandling
Vi bør kanskje gjøre en validering på disse Inngangsvilkårene? Visse av de kan kanskje ikke saksbehandler sende inn?

2023-01-26 12:30 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandlingshistorikk.kt
> +    data class OppdatertVilkår(val inngangsvilkår: Inngangsvilkår) : SøknadsbehandlingsHandling
Og hvis man skal være pedantisk, så tar ikke saksbehandler stilling til formuevilkåret. De har kun mulighet til å justere selve verdiene.

2023-01-26 12:31 UTC, hestad requested changes
Visse ting bør sees nøyere på. F.eks. forholdet mellom handling og inngangsvilkår. Og det at vi får ekstra fradrag ved beregning.

2023-01-26 12:39 UTC, RamziAbuQassim commented on database/src/main/kotlin/no/nav/su/se/bakover/database/søknadsbehandling/SøknadsbehandlingHistorikkJson.kt
> +    Formue,
oi, det var en skikkelig glipp ja

2023-01-26 12:51 UTC, RamziAbuQassim commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Saksbehandlingshistorikk.kt
> +    fun leggTilNyeHendelser(saksbehandlingsHendelse: List<T>): Saksbehandlingshistorikk<T>
ja, jeg tenkte litt på det selv

2023-01-27 07:56 UTC, RamziAbuQassim commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandlingshistorikk.kt
> +    data class OppdatertVilkår(val inngangsvilkår: Inngangsvilkår) : SøknadsbehandlingsHandling
Var det derfor jeg kanskje hadde Formue biten som en handling? 🤔 det husker jeg ikke. men det det høres ihvertfall sånn!

2023-01-28 12:11 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
> +        saksbehandler: NavIdentBruker.Saksbehandler,
Synes kanskje ikke vi skal sende med saksbehandler her. Det er jo ikke saksbehandleren som utfører operasjonene rundt avkorting og bør da heller ikke få navnet sitt knyttet til de operasjonene

2023-01-28 12:11 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
>          saksbehandler: NavIdentBruker.Saksbehandler,
Se kommentar nedenfor angående saksbehandler for operasjoner utført av systemet.

2023-01-28 12:11 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
> +    // TODO - kan sikkert gjøre noe med denne og attesteringer?
Bør enten fjerne kommentaren eller utdype et eksempel

2023-01-28 12:12 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
> +     * Ideelt sett så ville vi ikke tatt inn hendelse, men pga vi har mistet contexten på dette tidspunktet, så tar vi den inn
Ja, vi bør se på å dele opp denne i 2 forskjellige funksjoner.

2023-01-28 12:13 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
> +        // TODO: default til this.søkandshistorikk
Skal denne fremdeles gjøres?

2023-01-28 12:14 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
> +     * Selv om begge public funskjonene for leggTilOpplysningsplikt tar inn saksbehandler.
Vi bør gjøre om så den ikke tar inn saksbehandler, der ikke saksbehandler har utført handlingen.

2023-01-28 12:15 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
> +     * Den andre funksjonen [leggTilOpplysningspliktVilkår], brukes saksbehandler fordi det er påkrevd for vilkårsvurdering
Foreslår at vi ikke har saksbehandler som required når vi vilkårsvurderer da.

2023-01-30 11:58 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
> +     * Selv om begge public funskjonene for leggTilOpplysningsplikt tar inn saksbehandler
Den javadocen er vel litt utdatert nå?

2023-01-30 12:05 UTC, hestad approved these changes

2023-01-30 12:09 UTC, merged