mulighet for å lage fullstendig bosituasjon ved 1 endepunkt for søknadsbehandling
navikt/su-se-bakover pull request #1323
Opened 2023-03-28 09:07 UTC by RamziAbuQassim

2023-03-28 15:56 UTC, hestad commented on common/src/main/kotlin/no/nav/su/se/bakover/common/infrastructure/web/Feilresponser.kt
> +    val inneholderUfullstendigeBosituasjoner = BadRequest.errorJson(
Blanding mellom flertall og entall

2023-03-28 16:13 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
> +                if (grunnlagsdata.bosituasjon.inneholderUfullstendigeBosituasjoner()) {
Mulig å legge en wrapper-funksjon på grunnlagsdata også

2023-03-28 16:20 UTC, hestad commented on service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
> +        val søknadsbehandlingFraBasenFørStatusovergang = søknadsbehandlingRepo.hent(request.behandlingId)?.let {
Hva mener du med før statusovergang? Den utfører jo statusovergang inne i .let{}

2023-03-28 16:23 UTC, hestad commented on service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
> +            if (request.bosituasjoner.size > 1) {
Gjetter på dette er kopiert/flyttet, men generelt sett så hører ikke denne domenelogikken hjemme her i servicen.

2023-03-28 16:26 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/Application.kt
> +                        accessProtectedServices.revurdering,
Bør ikke generalisere på route-nivå. søknadsbehandling/revurdering bør ha hver sine service-filer. Nevnte service-filer kan bruke noe felles så klart.

2023-03-28 16:27 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/KunneIkkeLageGrunnlagsdata.kt
> +import no.nav.su.se.bakover.web.routes.søknadsbehandling.tilResultat
generic feil peker på spesifikk søknadsbehandling :shrug:

2023-03-28 16:30 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/LeggTilGrunnlagBosituasjonRoute.kt
Jeg foreslår heller å ha minst mulig endepunktsfiler i revurdering/søknadsbehandling. De kan godt bruke felles funksjoner og typer fra denne fila. Denne fila får ikke ha bruke ordet revurdering eller behandling

2023-03-28 16:33 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
> +private fun ValideringsfeilAttestering.tilResultat(): Resultat = when (this) {
Ligger denne i SøknadRoutes.kt?

2023-03-28 16:34 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
> +internal fun KunneIkkeAvslåSøknad.tilResultat(): Resultat = when (this) {
Hvilke andre endepunkt bruker denne?

2023-03-28 16:36 UTC, hestad commented on database/src/main/kotlin/no/nav/su/se/bakover/database/søknadsbehandling/SøknadsbehandlingshistorikkJson.kt
> +        OppdatertBosituasjon -> SøknadsbehandlingsHandling.OppdatertBosituasjon
Kan sikkert dokumentere forskjellen på TattStillingTilEPS, FullførtBosituasjonog denne. Historikken og planene videre.

2023-03-28 16:37 UTC, hestad requested changes
Spesielt den biten som sauser revurdering og søknadsbehandling mer sammen.

2023-03-30 10:21 UTC, RamziAbuQassim commented on service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
> +        val søknadsbehandlingFraBasenFørStatusovergang = søknadsbehandlingRepo.hent(request.behandlingId)?.let {
Nei, statusovergang gir en Either. Ikke sikkert den ble utført. Derfor gjør jeg en getOrElse under

2023-03-30 10:44 UTC, RamziAbuQassim commented on service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceImpl.kt
> +            if (request.bosituasjoner.size > 1) {
Løsningen blir vel å ha 2 funksjoner, en som tar liste og sjekker selv, og en som bare tar 1 bosituasjon i domenet 🤷

2023-03-30 11:17 UTC, RamziAbuQassim commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
> +private fun ValideringsfeilAttestering.tilResultat(): Resultat = when (this) {
Ja, pga AvslagPgaManglendeDokumentasjon er inne i denne routen

2023-03-30 11:18 UTC, RamziAbuQassim commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknad/SøknadRoutes.kt
> +internal fun KunneIkkeAvslåSøknad.tilResultat(): Resultat = when (this) {
Bare denne

2023-03-31 10:04 UTC, merged