Gjør grunnlagsdata sin trycreate til en Either
navikt/su-se-bakover pull request #451
Opened 2021-08-31 12:37 UTC by RamziAbuQassim

Før så kastet vi exception

2021-08-31 14:02 UTC, hestad commented on database/src/test/kotlin/no/nav/su/se/bakover/database/TestDataHelper.kt
> +    ).getOrHandle { throw IllegalStateException(it.toString()) }
Kan lage en felles extension function i samme mappe som denne. fun Grunnlagsdata.create(...) som kaller tryCreate og kaster slik du gjør her

2021-08-31 14:05 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/grunnlag/Grunnlagsdata.kt
> +        val IkkeVurdert = tryCreate().getOrHandle { throw IllegalStateException(it.toString()) }
Her kan du kanskje kalle konstruktøren direkte? tryCreate bør vel ikke ha default verdier til emptyList heller.

2021-08-31 14:07 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
> +            KunneIkkeLageGrunnlagsdata.FradragForEpsSomIkkeHarEPS -> KunneIkkeUtføreHandling.FradragForEpsSomIkkeHarEPS
Her er det helt ok å bruke domeneklassen KunneIkkeLageGrunnlagsdata videre. Den kan du i praksis eksponere til alle modulene. Kan bare wrappe den inn i en data class ved siden av UgyldigTilstand

2021-08-31 14:08 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
> +    open fun oppdaterUføreOgMarkerSomVurdert(uføre: Vilkår.Uførhet.Vurdert): Either<KunneIkkeUtføreHandling, OpprettetRevurdering> {
```suggestion
    open fun oppdaterUføreOgMarkerSomVurdert(uføre: Vilkår.Uførhet.Vurdert): Either<KunneIkkeOppdatereUføre, OpprettetRevurdering> {
```

2021-08-31 14:10 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
> +    open fun oppdaterUføreOgMarkerSomVurdert(uføre: Vilkår.Uførhet.Vurdert): Either<KunneIkkeUtføreHandling, OpprettetRevurdering> {
Når jeg tenker meg om burde vel ikke denne linjen vært endret? Uføre og Formue er vel vilkårsvurderinger og ikke grunnlagsdata?

Uansett tenker jeg det er helt fair at de har hver sin.

2021-08-31 14:13 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/søknadsbehandling/Søknadsbehandling.kt
> +        object MåLeggeTilBosituasjonFørFradrag : KunneIkkeLeggeTilFradragsgrunnlag()
Disse 3 kan slås sammen til en data class som wrapper Grunnlags-feilen

2021-08-31 14:14 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/GjeldendeVedtaksdata.kt
> +        ).getOrHandle { throw IllegalStateException(it.toString()) }
Kan legge på en TODO at denne og bør ha en tryCreate

2021-08-31 14:16 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Vedtak.kt
> +                        ).getOrHandle { throw IllegalStateException(it.toString()) },
Siden vi gjør dette fler ganger i prod-koden kunne vi vurdert et create() på siden av tryCreate :shrug:

2021-09-01 08:54 UTC, hestad commented on database/src/main/kotlin/no/nav/su/se/bakover/database/revurdering/RevurderingPostgresRepo.kt
> +        ).getOrHandle { throw IllegalStateException(it.toString()) }
Kan bytte til create()

2021-09-01 09:21 UTC, hestad requested changes

2021-09-01 09:21 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Vedtak.kt
> +                        ).getOrHandle { throw IllegalStateException(it.toString()) },
Kan bytte til create

2021-09-01 09:21 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
> +    val kunneIkkeLageFradragsgrunnlag = BadRequest.errorJson(
Missmatch mellom variabelnavn og feiltype. Burde kanskje hete noe som kunneIkkeLeggeTilFradragsgrunnlag/kunneIkkeLeggeTilBosituasjon (ikke lage/lagre)

2021-09-01 09:21 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilBosituasjonRevurderingRoute.kt
> +    is KunneIkkeLeggeTilBosituasjongrunnlag.KunneIkkeEndreFradragsgrunnlag -> Feilresponser.kunneIkkeLageFradragsgrunnlag
Mismatch mellom KunneIkkeLeggeTilBosituasjongrunnlag og KunneIkkeEndreFradragsgrunnlag

2021-09-01 09:21 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilFormueRevurderingRoute.kt
> +    is KunneIkkeLeggeTilFormuegrunnlag.KunneIkkeEndreFradragsgrunnlag -> Feilresponser.kunneIkkeLageFradragsgrunnlag
Hvordan endte denne opp her?

2021-09-01 09:21 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/revurdering/LeggTilUføreRevurderingRoutes.kt
> +                                            is KunneIkkeLeggeTilGrunnlag.KunneIkkeEndreFradragsgrunnlag -> Feilresponser.kunneIkkeLageFradragsgrunnlag
Denne skulle vel ikke vært her

2021-09-01 09:21 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilGrunnlagBosituasjonRoutes.kt
> +                                        is SøknadsbehandlingService.KunneIkkeLeggeTilBosituasjonEpsGrunnlag.KunneIkkeEndreFradragsgrunnlag -> Feilresponser.kunneIkkeLageFradragsgrunnlag
Mismatch mellom bosituasjon->fradrag

2021-09-01 09:21 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilGrunnlagBosituasjonRoutes.kt
> +                                        is SøknadsbehandlingService.KunneIkkeFullføreBosituasjonGrunnlag.KunneIkkeEndreFradragsgrunnlag -> Feilresponser.kunneIkkeLageBosituasjon
mismatch her og

2021-09-01 09:21 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilGrunnlagFradragRoutes.kt
> +                                            is KunneIkkeLeggeTilFradragsgrunnlag.KunneIkkeEndreFradragsgrunnlag -> Feilresponser.kunneIkkeLageBosituasjon
Mismatch

2021-09-01 09:41 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/revurdering/Revurdering.kt
> +        data class KunneIkkeEndreFradragsgrunnlag(val feil: KunneIkkeLageGrunnlagsdata) : KunneIkkeLeggeTilFradrag()
```suggestion
        data class Valideringsfeil(val feil: KunneIkkeLageGrunnlagsdata) : KunneIkkeLeggeTilFradrag()
```

2021-09-01 09:57 UTC, hestad commented on service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingService.kt
> +        data class KunneIkkeEndreFradragsgrunnlag(val feil: KunneIkkeLageGrunnlagsdata) : KunneIkkeLeggeTilBosituasjonEpsGrunnlag()
mismatch bostiuasjon / fradrag

2021-09-01 09:59 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
> +    val KunneIkkeLeggeTilBosituasjongrunnlag = NotFound.errorJson(
```suggestion
    valkunneIkkeLeggeTilBosituasjonsgrunnlag = NotFound.errorJson(
```

2021-09-01 09:59 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
> +        "klarte_ikke_legge_til_bosituasjongrunnlag",
Hvordan ser denne koden ut i framover nå?

2021-09-01 10:00 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
> +        "kunne_ikke_legge_til_fradragsgrunnlag",
Hvordan ser denne koden ut i framover nå?

2021-09-01 11:27 UTC, RamziAbuQassim commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
> +        "klarte_ikke_legge_til_bosituasjongrunnlag",
Tar en runde på dem snart

2021-09-01 11:30 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
> +    val KunneIkkeLeggeTilBosituasjonsgrunnlag = NotFound.errorJson(
```suggestion
    val kunneIkkeLeggeTilBosituasjonsgrunnlag = NotFound.errorJson(
```

2021-09-01 11:34 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
> +        "klarte_ikke_legge_til_bosituasjongrunnlag",
```suggestion
        "kunne_ikke_legge_til_bosituasjonsgrunnlag",
```

2021-09-01 11:34 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
> +        "Kunne ikke legge til bosituasjongrunnlag",
```suggestion
        "Kunne ikke legge til bosituasjonsgrunnlag",
```

2021-09-01 12:04 UTC, hestad commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/Feilresponser.kt
> +        "klarte_ikke_legge_til_bosituasjonsgrunnlag",
s/klarte/kunne ?

2021-09-01 12:27 UTC, hestad approved these changes

2021-09-01 12:28 UTC, merged