Avslagsgrunner
navikt/su-se-bakover pull request #58
Opened 2020-09-29 13:03 UTC by aryani1

Avslå behandling om beregnet beløp antingen er:

* 0kr
* Under minstebeløp for utbetaling, vilket er 2% av full supplerende stønad

2020-09-29 13:13 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlingsinformasjon.kt
> +    var uførhet: Uførhet? = null,
val til var? :cry:

2020-09-29 13:14 UTC, aryani1 commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/behandling/Behandlingsinformasjon.kt
> +    var uførhet: Uførhet? = null,
oops 🙈 skal fixa det

2020-09-29 13:19 UTC, hestad commented on domain/src/test/kotlin/no/nav/su/se/bakover/domain/BehandlingTest.kt
> +            vilkårsvurdertInnvilget.uførhet = Behandlingsinformasjon.Uførhet(Behandlingsinformasjon.Uførhet.Status.VilkårOppfylt, 1, 600000)
Du kan bruke .copy(uførhet=...)

2020-09-29 13:58 UTC, hestad commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
> +        månedsberegninger.sumBy { it.beløp } == 0
Kan beløpet været negativt? :p

2020-09-29 13:59 UTC, hestad approved these changes

2020-09-29 14:22 UTC, aryani1 commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
> +        månedsberegninger.sumBy { it.beløp } == 0
Tror inte det, har testat massa forskjellige värden men fått som minst 0. 🤔

2020-09-30 06:15 UTC, jacob-meidell requested changes

2020-09-30 06:15 UTC, jacob-meidell commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
> +    fun beløpErOverNullMenUnderMinstebeløp(): Boolean {
Denne funksjonen inneholder vel et par kritiske brister?
1. Funksjonen sjekker aldri at beløpet faktisk er større enn 0
2. "Gjennomsnittet" er ikke et gjennomsnitt, men en akkumulert sum.

Dersom objektet som eier denne funksjonen hadde hatt noen tester hadde vi kanskje fanget opp dette..?

2020-09-30 07:17 UTC, aryani1 commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
> +    fun beløpErOverNullMenUnderMinstebeløp(): Boolean {
Ja, gick lite snabbt där 😅 Den blev ändrad på ganska ofta och glömde uppdatera variabelnavn etc. Skal fixa det!

2020-09-30 07:35 UTC, christianmosveen requested changes

2020-09-30 07:35 UTC, christianmosveen commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
> +        val gjennomsnittPerMåned = månedsberegninger.sumBy { it.beløp }
```suggestion
        val beregnetBeløp = månedsberegninger.sumBy { it.beløp }
```

2020-09-30 07:35 UTC, christianmosveen commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
> +        return gjennomsnittPerMåned < minstebeløp
```suggestion
        return beregnetBeløp > 0 && beregnetBeløp < minstebeløp
```

2020-09-30 07:35 UTC, christianmosveen commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
> +        månedsberegninger.sumBy { it.beløp } == 0
Skader jo ikke å erstatte den med en `<=`.

2020-09-30 07:35 UTC, christianmosveen commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/beregning/Beregning.kt
> +    fun beløpErOverNullMenUnderMinstebeløp(): Boolean {
Hadde vært fint med en test på denne ja, den kan også avdekke eventuelle off-by-one eller avrundingsfeil.

2020-09-30 07:48 UTC, closed without merging

2020-09-30 07:51 UTC, aryani1 commented
Skal fikse lite ting och lagar ny senare!