Familiegjenforening vilkår
navikt/su-se-bakover pull request #896
Opened 2022-06-15 11:40 UTC by RamziAbuQassim

2022-06-15 13:05 UTC, jacob-meidell requested changes
Finner ikke noe repo-kode? Kan like godt implementere det for revurdering i samme slengen!

2022-06-15 13:05 UTC, jacob-meidell commented on service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceLeggTilFamiliegjenforeningTest.kt
> +internal class SøknadsbehandlingServiceLeggTilFamiliegjenforeningTest {
Gjør meg ingenting om du bare erstatter disse med en integrasjonstest via http-request.

2022-06-15 13:05 UTC, jacob-meidell commented on web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilFamiliegjenforeningRoutesTest.kt
> +    fun `ok request`() {
Denne kan man ihvertfall erstatte med en integrajsonstest.

2022-06-16 09:41 UTC, RamziAbuQassim commented on domain/src/test/kotlin/no/nav/su/se/bakover/domain/vilkår/FamiliegjenforeningTest.kt
> +    inner class Hybrid {
😂😂😂😂😂😂😂😂

2022-06-16 09:47 UTC, RamziAbuQassim commented on domain/src/test/kotlin/no/nav/su/se/bakover/domain/grunnlag/SjekkOmGrunnlagErKonsistentTest.kt
> +                formuegrunnlag = innvilgetFormueVilkårMedEnsligBosituasjon(
hmm ja :) vi hadde 2 funksjoner med samme navn, men intellij bestemte seg hele tiden for å bruke den andre.
Ser ut som den andre skulle egentlig være private(? - brukes bare i funksjonen over). det fikser vel problemet

2022-06-16 10:01 UTC, RamziAbuQassim commented on service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingService.kt
> +    sealed interface KunneIkkeLeggeTilFamiliegjenforeningVilkårService {
slipper å ha lange imports et par steder, samtidig så blir det mindre forvirrende om hvilken import er hvilken når dem alle har samme navn. synes jeg ihvertfall :)

2022-06-17 08:40 UTC, RamziAbuQassim commented on service/src/test/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingServiceLeggTilFamiliegjenforeningTest.kt
> +internal class SøknadsbehandlingServiceLeggTilFamiliegjenforeningTest {
¯\_(ツ)_/¯

2022-06-17 08:40 UTC, RamziAbuQassim commented on web/src/test/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilFamiliegjenforeningRoutesTest.kt
> +    fun `ok request`() {
¯\_(ツ)_/¯

2022-06-17 11:27 UTC, jacob-meidell commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vedtak/Stønadsvedtak.kt
> +            vilkårsvurderinger.familiegjenforening().getOrHandle { throw IllegalArgumentException(it.toString()) }
Føles mer naturlig å bare returnere either hele veien her?

2022-06-17 11:27 UTC, jacob-meidell commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/Vilkår.kt
> +                    is FamiliegjenforeningVilkår.Vurdert -> vilkår.vurderingsperioder.map { it.periode }
Følg samme syle som resten av funksjonen?

2022-06-17 11:27 UTC, jacob-meidell commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/Vilkår.kt
> +            val pensjon: PensjonsVilkår = PensjonsVilkår.IkkeVurdert,
Gjerne behold samme rekkefølgen overalt, blir litt enklere å følge med (ctor. + vilkårset+ tidslinje...etc)

2022-06-17 11:27 UTC, jacob-meidell commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/Vilkår.kt
> +                    is FamiliegjenforeningVilkår,
Ikke veldig viktig, men prøvde å skille de vilkårene som er tenkt at vi skal kunne bruke for uføre de som aldri skal brukes for uføre når jeg la til pensjon, kunne vurdert om du ville følge det.

2022-06-17 11:27 UTC, jacob-meidell commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/Vilkår.kt
> +                is FamiliegjenforeningVilkår -> Avslagsgrunn.FAMILIEGJENFORENING
Følg style?

2022-06-17 11:27 UTC, jacob-meidell commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/VurderingsperiodeFamiliegjenforening.kt
> +    override val grunnlag: Grunnlag? = null, // TODO - se om familiegjenforening skal ha et grunnlag
TBD?

2022-06-17 11:27 UTC, jacob-meidell commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/VurderingsperiodeFamiliegjenforening.kt
> +        other is VurderingsperiodeFamiliegjenforening && resultat == other.resultat && grunnlag == other.grunnlag
`grunnlag.erLik(other.grunnlag)`

2022-06-17 11:27 UTC, jacob-meidell commented on service/src/main/kotlin/no/nav/su/se/bakover/service/søknadsbehandling/SøknadsbehandlingService.kt
> +    sealed interface KunneIkkeLeggeTilFamiliegjenforeningVilkårService {
Hvis det gir veldig unaturlige navn på klassene kunne du evt prøvd deg med et `typealias` i de filene hvor det er konflikt

2022-06-17 11:27 UTC, jacob-meidell commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/grunnlag/GrunnlagsdataOgVilkårsvurderingerJson.kt
> +                familiegjenforening = vilkårsvurderinger.familiegjenforening().fold({ null }, { it.toJson() }),
følg style?

2022-06-17 12:10 UTC, RamziAbuQassim commented on database/src/main/kotlin/no/nav/su/se/bakover/database/grunnlag/FamiliegjenforeningVilkårsvurderingPostgresRepo.kt
> +                FamiliegjenforeningVilkår.IkkeVurdert -> {}
Det finnes ikke et grunnlag for familiegjenforening, så dette blir ikke et problem

2022-06-17 12:10 UTC, RamziAbuQassim commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/VurderingsperiodeFamiliegjenforening.kt
> +    override val grunnlag: Grunnlag? = null, // TODO - se om familiegjenforening skal ha et grunnlag
fjernet TODO. finnes ikke et grunnlag :)

2022-06-17 12:16 UTC, RamziAbuQassim commented on domain/src/main/kotlin/no/nav/su/se/bakover/domain/vilkår/VurderingsperiodeFamiliegjenforening.kt
> +            grunnlag = null,
den eksisterer ikke. Men vi burde kanskje lage en i baseklassen. Noen av grunnlagene har litt spesialhåndtering på det da

2022-06-17 12:18 UTC, RamziAbuQassim commented on test-common/src/main/kotlin/VilkårsvurderingerTestData.kt
> +fun vilkårsvurderingSøknadsbehandlingIkkeVurdertAlder() = Vilkårsvurderinger.Søknadsbehandling.Alder(
wups, der var det noe feil ja :)

2022-06-17 13:09 UTC, RamziAbuQassim commented on web/src/main/kotlin/no/nav/su/se/bakover/web/routes/søknadsbehandling/LeggTilFamiliegjenforeningRoute.kt
> +internal fun Route.leggTilFamiliegjenforeningRoute(
kan ta det når vi begynner med revurdering

2022-06-20 11:12 UTC, RamziAbuQassim commented
merger inn!

2022-06-20 11:12 UTC, merged